<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

/**
 * Class CurrencySeeder
 */
class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Currency::insert($this->getCurrencies());
    }

    /**
     * Return list of currencies.
     *
     * @return array
     */
    protected function getCurrencies()
    {
        return [
            ['code' => 'AED', 'currency' => 'UAE Dirham', 'symbol' => null,],
            ['code' => 'AFN', 'currency' => 'Afghani', 'symbol' => null,],
            ['code' => 'ALL', 'currency' => 'Lek', 'symbol' => null,],
            ['code' => 'AMD', 'currency' => 'Armenian Dram', 'symbol' => null,],
            ['code' => 'ANG', 'currency' => 'Netherlands Antillean Guilder', 'symbol' => null,],
            ['code' => 'AOA', 'currency' => 'Kwanza', 'symbol' => null,],
            ['code' => 'ARS', 'currency' => 'Argentine Peso', 'symbol' => null,],
            ['code' => 'AUD', 'currency' => 'Australian Dollar', 'symbol' => null,],
            ['code' => 'AWG', 'currency' => 'Aruban Florin', 'symbol' => null,],
            ['code' => 'AZN', 'currency' => 'Azerbaijanian Manat', 'symbol' => null,],
            ['code' => 'BAM', 'currency' => 'Convertible Mark', 'symbol' => null,],
            ['code' => 'BBD', 'currency' => 'Barbados Dollar', 'symbol' => null,],
            ['code' => 'BDT', 'currency' => 'Taka', 'symbol' => null,],
            ['code' => 'BGN', 'currency' => 'Bulgarian Lev', 'symbol' => null,],
            ['code' => 'BHD', 'currency' => 'Bahraini Dinar', 'symbol' => null,],
            ['code' => 'BIF', 'currency' => 'Burundi Franc', 'symbol' => null,],
            ['code' => 'BMD', 'currency' => 'Bermudian Dollar', 'symbol' => null,],
            ['code' => 'BND', 'currency' => 'Brunei Dollar', 'symbol' => null,],
            ['code' => 'BOB', 'currency' => 'Boliviano', 'symbol' => null,],
            ['code' => 'BOV', 'currency' => 'Mvdol', 'symbol' => null,],
            ['code' => 'BRL', 'currency' => 'Brazilian Real', 'symbol' => null,],
            ['code' => 'BSD', 'currency' => 'Bahamian Dollar', 'symbol' => null,],
            ['code' => 'BTN', 'currency' => 'Ngultrum', 'symbol' => null,],
            ['code' => 'BWP', 'currency' => 'Pula', 'symbol' => null,],
            ['code' => 'BYN', 'currency' => 'Belarussian Ruble', 'symbol' => null,],
            ['code' => 'BZD', 'currency' => 'Belize Dollar', 'symbol' => null,],
            ['code' => 'CAD', 'currency' => 'Canadian Dollar', 'symbol' => null,],
            ['code' => 'CDF', 'currency' => 'Congolese Franc', 'symbol' => null,],
            ['code' => 'CHE', 'currency' => 'WIR Euro', 'symbol' => null,],
            ['code' => 'CHF', 'currency' => 'Swiss Franc', 'symbol' => null,],
            ['code' => 'CHW', 'currency' => 'WIR Franc', 'symbol' => null,],
            ['code' => 'CLF', 'currency' => 'Unidad de Fomento', 'symbol' => null,],
            ['code' => 'CLP', 'currency' => 'Chilean Peso', 'symbol' => null,],
            ['code' => 'CNY', 'currency' => 'Yuan Renminbi', 'symbol' => null,],
            ['code' => 'COP', 'currency' => 'Colombian Peso', 'symbol' => null,],
            ['code' => 'COU', 'currency' => 'Unidad de Valor Real', 'symbol' => null,],
            ['code' => 'CRC', 'currency' => 'Costa Rican Colon', 'symbol' => null,],
            ['code' => 'CUC', 'currency' => 'Peso Convertible', 'symbol' => null,],
            ['code' => 'CUP', 'currency' => 'Cuban Peso', 'symbol' => null,],
            ['code' => 'CVE', 'currency' => 'Cabo Verde Escudo', 'symbol' => null,],
            ['code' => 'CZK', 'currency' => 'Czech Koruna', 'symbol' => null,],
            ['code' => 'DJF', 'currency' => 'Djibouti Franc', 'symbol' => null,],
            ['code' => 'DKK', 'currency' => 'Danish Krone', 'symbol' => null,],
            ['code' => 'DOP', 'currency' => 'Dominican Peso', 'symbol' => null,],
            ['code' => 'DZD', 'currency' => 'Algerian Dinar', 'symbol' => null,],
            ['code' => 'EGP', 'currency' => 'Egyptian Pound', 'symbol' => null,],
            ['code' => 'ERN', 'currency' => 'Nakfa', 'symbol' => null,],
            ['code' => 'ETB', 'currency' => 'Ethiopian Birr', 'symbol' => null,],
            ['code' => 'EUR', 'currency' => 'Euro', 'symbol' => '€',],
            ['code' => 'FJD', 'currency' => 'Fiji Dollar', 'symbol' => null,],
            ['code' => 'FKP', 'currency' => 'Falkland Islands Pound', 'symbol' => null,],
            ['code' => 'GBP', 'currency' => 'Pound Sterling', 'symbol' => '£',],
            ['code' => 'GEL', 'currency' => 'Lari', 'symbol' => null,],
            ['code' => 'GHS', 'currency' => 'Ghana Cedi', 'symbol' => null,],
            ['code' => 'GIP', 'currency' => 'Gibraltar Pound', 'symbol' => null,],
            ['code' => 'GMD', 'currency' => 'Dalasi', 'symbol' => null,],
            ['code' => 'GNF', 'currency' => 'Guinea Franc', 'symbol' => null,],
            ['code' => 'GTQ', 'currency' => 'Quetzal', 'symbol' => null,],
            ['code' => 'GYD', 'currency' => 'Guyana Dollar', 'symbol' => null,],
            ['code' => 'HKD', 'currency' => 'Hong Kong Dollar', 'symbol' => null,],
            ['code' => 'HNL', 'currency' => 'Lempira', 'symbol' => null,],
            ['code' => 'HRK', 'currency' => 'Kuna', 'symbol' => null,],
            ['code' => 'HTG', 'currency' => 'Gourde', 'symbol' => null,],
            ['code' => 'HUF', 'currency' => 'Forint', 'symbol' => null,],
            ['code' => 'IDR', 'currency' => 'Rupiah', 'symbol' => null,],
            ['code' => 'ILS', 'currency' => 'New Israeli Sheqel', 'symbol' => null,],
            ['code' => 'INR', 'currency' => 'Indian Rupee', 'symbol' => null,],
            ['code' => 'IQD', 'currency' => 'Iraqi Dinar', 'symbol' => null,],
            ['code' => 'IRR', 'currency' => 'Iranian Rial', 'symbol' => null,],
            ['code' => 'ISK', 'currency' => 'Iceland Krona', 'symbol' => null,],
            ['code' => 'JMD', 'currency' => 'Jamaican Dollar', 'symbol' => null,],
            ['code' => 'JOD', 'currency' => 'Jordanian Dinar', 'symbol' => null,],
            ['code' => 'JPY', 'currency' => 'Yen', 'symbol' => null,],
            ['code' => 'KES', 'currency' => 'Kenyan Shilling', 'symbol' => null,],
            ['code' => 'KGS', 'currency' => 'Som', 'symbol' => null,],
            ['code' => 'KHR', 'currency' => 'Riel', 'symbol' => null,],
            ['code' => 'KMF', 'currency' => 'Comoro Franc', 'symbol' => null,],
            ['code' => 'KPW', 'currency' => 'North Korean Won', 'symbol' => null,],
            ['code' => 'KRW', 'currency' => 'Won', 'symbol' => null,],
            ['code' => 'KWD', 'currency' => 'Kuwaiti Dinar', 'symbol' => null,],
            ['code' => 'KYD', 'currency' => 'Cayman Islands Dollar', 'symbol' => null,],
            ['code' => 'KZT', 'currency' => 'Tenge', 'symbol' => null,],
            ['code' => 'LAK', 'currency' => 'Kip', 'symbol' => null,],
            ['code' => 'LBP', 'currency' => 'Lebanese Pound', 'symbol' => null,],
            ['code' => 'LKR', 'currency' => 'Sri Lanka Rupee', 'symbol' => null,],
            ['code' => 'LRD', 'currency' => 'Liberian Dollar', 'symbol' => null,],
            ['code' => 'LSL', 'currency' => 'Loti', 'symbol' => null,],
            ['code' => 'LYD', 'currency' => 'Libyan Dinar', 'symbol' => null,],
            ['code' => 'MAD', 'currency' => 'Moroccan Dirham', 'symbol' => null,],
            ['code' => 'MDL', 'currency' => 'Moldovan Leu', 'symbol' => null,],
            ['code' => 'MGA', 'currency' => 'Malagasy Ariary', 'symbol' => null,],
            ['code' => 'MKD', 'currency' => 'Denar', 'symbol' => null,],
            ['code' => 'MMK', 'currency' => 'Kyat', 'symbol' => null,],
            ['code' => 'MNT', 'currency' => 'Tugrik', 'symbol' => null,],
            ['code' => 'MOP', 'currency' => 'Pataca', 'symbol' => null,],
            ['code' => 'MRU', 'currency' => 'Ouguiya', 'symbol' => null,],
            ['code' => 'MUR', 'currency' => 'Mauritius Rupee', 'symbol' => null,],
            ['code' => 'MVR', 'currency' => 'Rufiyaa', 'symbol' => null,],
            ['code' => 'MWK', 'currency' => 'Kwacha', 'symbol' => null,],
            ['code' => 'MXN', 'currency' => 'Mexican Peso', 'symbol' => null,],
            ['code' => 'MXV', 'currency' => 'Mexican Unidad de Inversion (UDI)', 'symbol' => null,],
            ['code' => 'MYR', 'currency' => 'Malaysian Ringgit', 'symbol' => null,],
            ['code' => 'MZN', 'currency' => 'Mozambique Metical', 'symbol' => null,],
            ['code' => 'NAD', 'currency' => 'Namibia Dollar', 'symbol' => null,],
            ['code' => 'NGN', 'currency' => 'Naira', 'symbol' => null,],
            ['code' => 'NIO', 'currency' => 'Cordoba Oro', 'symbol' => null,],
            ['code' => 'NOK', 'currency' => 'Norwegian Krone', 'symbol' => null,],
            ['code' => 'NPR', 'currency' => 'Nepalese Rupee', 'symbol' => null,],
            ['code' => 'NZD', 'currency' => 'New Zealand Dollar', 'symbol' => null,],
            ['code' => 'OMR', 'currency' => 'Rial Omani', 'symbol' => null,],
            ['code' => 'PAB', 'currency' => 'Balboa', 'symbol' => null,],
            ['code' => 'PEN', 'currency' => 'Nuevo Sol', 'symbol' => null,],
            ['code' => 'PGK', 'currency' => 'Kina', 'symbol' => null,],
            ['code' => 'PHP', 'currency' => 'Philippine Peso', 'symbol' => null,],
            ['code' => 'PKR', 'currency' => 'Pakistan Rupee', 'symbol' => null,],
            ['code' => 'PLN', 'currency' => 'Zloty', 'symbol' => null,],
            ['code' => 'PYG', 'currency' => 'Guarani', 'symbol' => null,],
            ['code' => 'QAR', 'currency' => 'Qatari Rial', 'symbol' => null,],
            ['code' => 'RON', 'currency' => 'Romanian Leu', 'symbol' => null,],
            ['code' => 'RSD', 'currency' => 'Serbian Dinar', 'symbol' => null,],
            ['code' => 'RUB', 'currency' => 'Russian Ruble', 'symbol' => null,],
            ['code' => 'RWF', 'currency' => 'Rwanda Franc', 'symbol' => null,],
            ['code' => 'SAR', 'currency' => 'Saudi Riyal', 'symbol' => null,],
            ['code' => 'SBD', 'currency' => 'Solomon Islands Dollar', 'symbol' => null,],
            ['code' => 'SCR', 'currency' => 'Seychelles Rupee', 'symbol' => null,],
            ['code' => 'SDG', 'currency' => 'Sudanese Pound', 'symbol' => null,],
            ['code' => 'SEK', 'currency' => 'Swedish Krona', 'symbol' => null,],
            ['code' => 'SGD', 'currency' => 'Singapore Dollar', 'symbol' => null,],
            ['code' => 'SHP', 'currency' => 'Saint Helena Pound', 'symbol' => null,],
            ['code' => 'SLL', 'currency' => 'Leone', 'symbol' => null,],
            ['code' => 'SOS', 'currency' => 'Somali Shilling', 'symbol' => null,],
            ['code' => 'SRD', 'currency' => 'Surinam Dollar', 'symbol' => null,],
            ['code' => 'SSP', 'currency' => 'South Sudanese Pound', 'symbol' => null,],
            ['code' => 'STN', 'currency' => 'Dobra', 'symbol' => null,],
            ['code' => 'SVC', 'currency' => 'El Salvador Colon', 'symbol' => null,],
            ['code' => 'SYP', 'currency' => 'Syrian Pound', 'symbol' => null,],
            ['code' => 'SZL', 'currency' => 'Lilangeni', 'symbol' => null,],
            ['code' => 'THB', 'currency' => 'Baht', 'symbol' => null,],
            ['code' => 'TJS', 'currency' => 'Somoni', 'symbol' => null,],
            ['code' => 'TMT', 'currency' => 'Turkmenistan New Manat', 'symbol' => null,],
            ['code' => 'TND', 'currency' => 'Tunisian Dinar', 'symbol' => null,],
            ['code' => 'TOP', 'currency' => 'Pa’anga', 'symbol' => null,],
            ['code' => 'TRY', 'currency' => 'Turkish Lira', 'symbol' => null,],
            ['code' => 'TTD', 'currency' => 'Trinidad and Tobago Dollar', 'symbol' => null,],
            ['code' => 'TWD', 'currency' => 'New Taiwan Dollar', 'symbol' => null,],
            ['code' => 'TZS', 'currency' => 'Tanzanian Shilling', 'symbol' => null,],
            ['code' => 'UAH', 'currency' => 'Hryvnia', 'symbol' => null,],
            ['code' => 'UGX', 'currency' => 'Uganda Shilling', 'symbol' => null,],
            ['code' => 'USD', 'currency' => 'US Dollar', 'symbol' => '$',],
            ['code' => 'USN', 'currency' => 'US Dollar (Next day)', 'symbol' => null,],
            ['code' => 'UYI', 'currency' => 'Uruguay Peso en Unidades Indexadas (URUIURUI)', 'symbol' => null,],
            ['code' => 'UYU', 'currency' => 'Peso Uruguayo', 'symbol' => null,],
            ['code' => 'UZS', 'currency' => 'Uzbekistan Sum', 'symbol' => null,],
            ['code' => 'VEF', 'currency' => 'Bolivar', 'symbol' => null,],
            ['code' => 'VND', 'currency' => 'Dong', 'symbol' => null,],
            ['code' => 'VUV', 'currency' => 'Vatu', 'symbol' => null,],
            ['code' => 'WST', 'currency' => 'Tala', 'symbol' => null,],
            ['code' => 'XAF', 'currency' => 'CFA Franc BEAC', 'symbol' => null,],
            ['code' => 'XCD', 'currency' => 'East Caribbean Dollar', 'symbol' => null,],
            ['code' => 'XDR', 'currency' => 'SDR (Special Drawing Right)', 'symbol' => null,],
            ['code' => 'XOF', 'currency' => 'CFA Franc BCEAO', 'symbol' => null,],
            ['code' => 'XPF', 'currency' => 'CFP Franc', 'symbol' => null,],
            ['code' => 'XSU', 'currency' => 'Sucre', 'symbol' => null,],
            ['code' => 'XUA', 'currency' => 'ADB Unit of Account', 'symbol' => null,],
            ['code' => 'YER', 'currency' => 'Yemeni Rial', 'symbol' => null,],
            ['code' => 'ZAR', 'currency' => 'Rand', 'symbol' => null,],
            ['code' => 'ZMW', 'currency' => 'Zambian Kwacha', 'symbol' => null,],
            ['code' => 'ZWL', 'currency' => 'Zimbabwe Dollar', 'symbol' => null,],
        ];
    }
}
