name: "Pull request labeler"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  triage:
    name: "Label PR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"